In [15]:
import numpy as np
import pandas as pd
import sys

In [37]:
a = [1, 2, 3]
b = a[0]
print(b is a[1])
b = 99
print(b is a[1])
print('a = {:s}, b = {:s}'.format(str(a),str(b)))

False
False
a = [1, 2, 3], b = 99


Initially b points to the same place in memory as a, but scalers are immutable, so `b=3` results in a new memory allocation because `3` is a scaler

In [38]:
a = [1, 2 ,3]
b = a
print(b is a)
b[0] = 99
print(b is a)
print('a = {:s}, b = {:s}'.format(str(a),str(b)))

True
True
a = [99, 2, 3], b = [99, 2, 3]


lists are mutables, so we can change an item in a list and keep the same space in memory

In [18]:
print(id(b), id(a))
print(sys.getrefcount(a))

140533790496320 140533790496320
3


We can check their memory ids and how many references there are. In this case 3, which is a little suprising, maybe it is counting the multiple calls in the prior two cells

In [39]:
a = np.array([1, 2, 3])
b = a
print(b is a)
b = b + 1
print(b is a)
print('a = {:s}, b = {:s}'.format(str(a),str(b)))

True
False
a = [1 2 3], b = [2 3 4]


Performing an operation appears to create a copy, b no longer points to a's spot in memory

In [43]:
a = np.array([1, 2, 3, 4])
b = a[:2]
print(b is a)
b[0] = 99
print(b is a)
print('a = {:s}, b = {:s}'.format(str(a),str(b)))

False
False
a = [99  2  3  4], b = [99  2]


Here b in a sublist, but still points as we'd expect

In [45]:
a = np.array([1, 2, 3, 4])
b = a[1]
b = 99
print('a = {:s}, b = {:s}'.format(str(a),str(b)))

a = [1 2 3 4], b = 99


Here b is an element of a, a scaler, which is immutable, and therefore a new copy

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([11, 12, 13, 14])
c = np.concatenate([a,b])
c[0] = 99`
print(a)

[1 2 3 4]


In [28]:
a = [1, 2, 3]
b = [11, 12, 13]
c = a + b
c[0] = 99
print(a)

[1, 2, 3]


In [40]:
a = np.array([1, 2, 3])
b = a
b[b<2] = 99
print(a)

[99  2  3]


In [54]:
a = np.array([1, 2, 3, np.nan])
b = a
b = b[~np.isnan(b)]
print(a)

[ 1.  2.  3. nan]


In [59]:
a = pd.DataFrame({'test':[1, 2, 3, np.nan]})
b = a
b.dropna(inplace=True)
print(a)

   test
0   1.0
1   2.0
2   3.0


In [61]:
a = pd.DataFrame({'test':[1, 2, 3, np.nan]})
b = a
b = b.dropna()
print(a)

   test
0   1.0
1   2.0
2   3.0
3   NaN


In [60]:
a = pd.DataFrame({'test':[1, 2, 3, np.nan]})
b = a
b = b[b.notnull()]
print(a)

   test
0   1.0
1   2.0
2   3.0
3   NaN


In [78]:
df = pd.DataFrame({'test':np.sin(np.arange(0,100,.0001))})
df.loc[df['test'] < -0.2] = np.nan

In [80]:
%%timeit
df2 = df.dropna(inplace=False)

15.3 ms ± 692 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [81]:
%%timeit
df.dropna(inplace=True)

11.6 ms ± 67.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
def replace_element(array, index, new_element):
    array[index] = new_element
    return array

a = np.array([1, 2, 3, 4])
b = a
c = replace_element(b, 1, 99)
print(a)

[ 1 99  3  4]


In [13]:
def replace_element(array, index, new_element):
    array[2] = array[2]*2
    return array

a = np.array([1, 2, 3, 4])
b = a
c = replace_element(b, 1, 99)
print(a)

[1 2 6 4]


In [14]:
def replace_element(array, index, new_element):
    array = array*2
    return array

a = np.array([1, 2, 3, 4])
b = a
c = replace_element(b, 1, 99)
print(a)

[1 2 3 4]


In [11]:
def replace_element(array, index, new_element):
    array = [9,9,9,9]
    return array

a = np.array([1, 2, 3, 4])
b = a
c = replace_element(b, 1, 99)
print(a)

[1 2 3 4]
