In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
np?

In [4]:
L = list(range(10))

In [5]:
type(L[0])

int

In [6]:
M = range(10)

In [7]:
import array

In [8]:
L = list(range(10))
A = array.array('i',L)

In [9]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
intarray=np.array([1,2,5,10])

In [11]:
type(intarray)

numpy.ndarray

In [12]:
farray = np.array([2.3, 1., 1.0])

In [13]:
type(farray)

numpy.ndarray

In [14]:
farray = np.array([2.3, 1., 1.0], dtype='float16')

In [15]:
farray

array([2.3, 1. , 1. ], dtype=float16)

In [16]:
m = np.array([range(i,i+4) for i in [10, 20, 100]])

In [17]:
m


array([[ 10,  11,  12,  13],
       [ 20,  21,  22,  23],
       [100, 101, 102, 103]])

In [18]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,4,2),dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [20]:
np.full((3,4),4.5)

array([[4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5]])

In [21]:
4.5*np.ones((3,4))

array([[4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5]])

In [22]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.linspace(1,5,37)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ,
       2.11111111, 2.22222222, 2.33333333, 2.44444444, 2.55555556,
       2.66666667, 2.77777778, 2.88888889, 3.        , 3.11111111,
       3.22222222, 3.33333333, 3.44444444, 3.55555556, 3.66666667,
       3.77777778, 3.88888889, 4.        , 4.11111111, 4.22222222,
       4.33333333, 4.44444444, 4.55555556, 4.66666667, 4.77777778,
       4.88888889, 5.        ])

In [24]:
np.random.random((1,3))

array([[0.07095224, 0.9511745 , 0.05518921]])

In [25]:
np.random.normal(0,1,(4,5))

array([[ 0.18824901,  0.0075877 ,  0.42575833, -0.67470852, -0.51228043],
       [-0.21585756, -0.02540172,  1.7085659 ,  0.03839497, -0.03498608],
       [-0.48516623,  3.07319709, -0.18450475, -0.07245426, -0.18268421],
       [ 1.03205037,  1.57300829, -0.30089338,  1.14595343, -0.98413031]])

In [26]:
np.random.normal?

In [27]:
np.mean(np.random.normal(0,1,(4,100)),axis=1)

array([-0.04231057, -0.11164809,  0.05002742, -0.09726935])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
a = np.array([1,3,4],dtype=np.float32)

In [30]:
a

array([1., 3., 4.], dtype=float32)

In [31]:
np.random.seed(0)

In [32]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [33]:
print('x3 ndim: {:d}'.format(x3.ndim))
print('x2 ndim: {:d}'.format(x2.ndim))
print('x1 ndim: {:d}'.format(x1.ndim))

x3 ndim: 3
x2 ndim: 2
x1 ndim: 1


In [34]:
x3.shape
x3.dtype
x3.nbytes

240

In [35]:
x3[0,1,2] = 1000

In [36]:
x3.nbytes

240

In [37]:
x3[:,:2,1]

array([[1, 4],
       [1, 7],
       [9, 9]])

In [38]:
x3[:,0,1]

array([1, 1, 9])

In [39]:
x4 = np.arange(10)

In [40]:
x4[9:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [41]:
x2[0]

array([3, 5, 2, 4])

In [42]:
x2[0,:]

array([3, 5, 2, 4])

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
x2s = x2[:2,:2]

In [45]:
x2s[:,:] = 2

In [46]:
x2

array([[2, 2, 2, 4],
       [2, 2, 8, 8],
       [1, 6, 7, 7]])

In [47]:
x2sc = x2[:2,:2].copy()

In [48]:
a = np.arange(1,10)

In [49]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
b = np.reshape(a,(3,3))

In [51]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
b[2,2] = 99

In [53]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99])

In [54]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [55]:
a = np.arange(1,4)

In [56]:
a = np.reshape(a,(1,3))

In [57]:
a.reshape((3,1))

array([[1],
       [2],
       [3]])

In [58]:
a.shape

(1, 3)

In [59]:
a

array([[1, 2, 3]])

In [60]:
a.shape

(1, 3)

In [62]:
x = np.array([1,2,3,4])
y = np.array([1,2,3,4])*2
np.vstack([x,y])

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [63]:
np.hstack([x,y])

array([1, 2, 3, 4, 2, 4, 6, 8])

In [64]:
np.concatenate([x,y],axis=0)

array([1, 2, 3, 4, 2, 4, 6, 8])

In [68]:
np.dstack([x,y])

array([[[1, 2],
        [2, 4],
        [3, 6],
        [4, 8]]])

In [71]:
x = np.arange(100)
[x1,x2,x3] = np.split(x,[33, 66])