In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [4]:
np?

In [5]:
L = list(range(10))

In [13]:
type(L[0])

int

In [7]:
M = range(10)

In [14]:
import array

In [15]:
L = list(range(10))
A = array.array('i',L)

In [16]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
intarray=np.array([1,2,5,10])

In [19]:
type(intarray)

numpy.ndarray

In [21]:
farray = np.array([2.3, 1., 1.0])

In [23]:
type(farray)

numpy.ndarray

In [24]:
farray = np.array([2.3, 1., 1.0], dtype='float16')

In [25]:
farray

array([2.3, 1. , 1. ], dtype=float16)

In [28]:
m = np.array([range(i,i+4) for i in [10, 20, 100]])

In [29]:
m


array([[ 10,  11,  12,  13],
       [ 20,  21,  22,  23],
       [100, 101, 102, 103]])

In [30]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones((3,4,2),dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [33]:
np.full((3,4),4.5)

array([[4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5]])

In [34]:
4.5*np.ones((3,4))

array([[4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5]])

In [35]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np.linspace(1,5,37)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ,
       2.11111111, 2.22222222, 2.33333333, 2.44444444, 2.55555556,
       2.66666667, 2.77777778, 2.88888889, 3.        , 3.11111111,
       3.22222222, 3.33333333, 3.44444444, 3.55555556, 3.66666667,
       3.77777778, 3.88888889, 4.        , 4.11111111, 4.22222222,
       4.33333333, 4.44444444, 4.55555556, 4.66666667, 4.77777778,
       4.88888889, 5.        ])

In [38]:
np.random.random((1,3))

array([[0.76679817, 0.46592251, 0.88960355]])

In [40]:
np.random.normal(0,1,(4,5))

array([[-0.33422191,  1.76343884, -2.22669879,  0.10535147,  0.47625199],
       [-0.34931165, -0.16795633,  0.96605372, -0.61709949,  1.38917492],
       [-1.57908951,  0.63391465, -0.39426929, -1.15104723,  0.25987079],
       [ 1.19093083,  0.33089547, -1.55438789, -0.24869646, -0.41253962]])

In [41]:
np.random.normal?

In [46]:
np.mean(np.random.normal(0,1,(4,100)),axis=1)

array([-0.02110344, -0.13229235, -0.05384519, -0.02925693])

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
a = np.array([1,3,4],dtype=np.float32)

In [50]:
a

array([1., 3., 4.], dtype=float32)

In [51]:
np.random.seed(0)

In [54]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [60]:
print('x3 ndim: {:d}'.format(x3.ndim))
print('x2 ndim: {:d}'.format(x2.ndim))
print('x1 ndim: {:d}'.format(x1.ndim))

x3 ndim: 3
x2 ndim: 2
x1 ndim: 1


In [64]:
x3.shape
x3.dtype
x3.nbytes

240

In [72]:
x3[0,1,2] = 1000

In [73]:
x3.nbytes

240

In [78]:
x3[:,:2,1]

array([[3, 3],
       [4, 4],
       [3, 6]])

In [79]:
x3[:,0,1]

array([3, 4, 3])

In [81]:
x4 = np.arange(10)

In [86]:
x4[9:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [87]:
x2[0]

array([8, 1, 5, 9])

In [88]:
x2[0,:]

array([8, 1, 5, 9])

In [89]:
x2

array([[8, 1, 5, 9],
       [8, 9, 4, 3],
       [0, 3, 5, 0]])

In [90]:
x2s = x2[:2,:2]

In [91]:
x2s[:,:] = 2

In [92]:
x2

array([[2, 2, 5, 9],
       [2, 2, 4, 3],
       [0, 3, 5, 0]])

In [93]:
x2sc = x2[:2,:2].copy()

In [94]:
a = np.arange(1,10)

In [95]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
b = np.reshape(a,(3,3))

In [98]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
b[2,2] = 99

In [101]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8, 99])

In [102]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [112]:
a = np.arange(1,4)

In [113]:
a = np.reshape(a,(1,3))

In [115]:
a.reshape((3,1))

array([[1],
       [2],
       [3]])

In [117]:
a.shape

(1, 3)

In [111]:
a

array([[1, 2, 3]])

In [110]:
a.shape

(1, 3)